prj2/emsapp/urls.py
"""
"""
from django.contrib import admin
from django.urls import path
from emsapp import views

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'emsapp'


urlpatterns = [

    path('list/', views.EmployeeListView.as_view(), name = 'list'),
    path('create/', views.EmployeeCreateView.as_view(), name = 'create'),
    path('edit/<int:pk>', views.EmployeeUpdateView.as_view(), name = 'edit'),
    path('update/<int:pk>', views.EmployeeUpdateView.as_view(), name = 'update'),
    path('delete/<int:pk>', views.EmployeeDeleteView.as_view(), name = 'delete'),
    path('details/<int:pk>', views.EmployeeDetailView.as_view(), name = 'details'),
   
]

prj2/myapp/urls.py
"""
"""
from django.contrib import admin
from django.urls import path
from myapp import views

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'myapp'


urlpatterns = [
   
    path('details/<int:id>', views.show, name = 'details'),
    path('index/', views.index, name = 'index'),
    path('create/', views.create, name = 'create'),
    path('edit/<int:id>', views.edit, name = 'edit'),
    path('update/<int:id>', views.update, name = 'update'),
    path('delete/<int:id>', views.delete, name = 'delete'),
    path('email/', views.sendEmail, name = 'email'),
    path('register/', views.user_register, name = 'register'),
    path('login/', views.user_login, name = 'login'),
    path('logout/', views.user_logout, name = 'logout'),
    path('exportdata/', views.exportdata, name = 'export'),
]

prj2/prj2/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('std/', include(('myapp.urls', 'app_name'), namespace = 'student')),
    path('', views.home, name = 'home'),
    path('emp/', include(('emsapp.urls', 'app_name'), namespace = 'employee')),
    
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

prj2/emsapp/models.py
from django.db import models
from datetime import datetime
# Create your models here.
class Department(models.Model):   
    id = models.AutoField(primary_key = True)
    name = models.CharField(max_length = 100)

    def __str__(self):
        return f"Name: {self.name}"

class Employee(models.Model):
    GENDER_CHOICES = [('Male', 'Male'),('Female', 'Female')]  #[(tuple)], ('Male', 'Male') one for desply one male for value
    id = models.AutoField(primary_key = True)
    name = models.CharField(max_length = 100)
    email = models.EmailField(unique = True, blank = True)
    dob = models.DateField(default = datetime.now, blank = True)
    gender = models.CharField(max_length = 6, choices = GENDER_CHOICES, default = 'Male', )
    salary = models.DecimalField(max_digits = 8, decimal_places = 2, blank = True, null = True)
    photo = models.FileField(upload_to = 'empimage', default = 'empimage/blank.png', blank = True)
    department = models.ForeignKey(Department, on_delete = models.CASCADE)

prj2/myapp/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
# Create your models here.
class Student(models.Model):

    GENDER_CHOICES = [('Male', 'Male'),('Female', 'Female')]  #[(tuple)], ('Male', 'Male') one for desply one male for value
    id = models.AutoField(primary_key = True)
    name = models.CharField(max_length = 100)
    email = models.EmailField(unique = True, blank = True)
    dob = models.DateField(default = datetime.now, blank = True)
    gender = models.CharField(max_length = 6, choices = GENDER_CHOICES, default = 'Male', )
    
    def __str__(self):
        return f"Id: {self.id} Name: {self.name}"

class UserProfile(models.Model):
    USER_CHOICES = [('Admin','Admin'),('Student','Student'),('Employee','Employee')]
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    profile_pic = models.FileField(upload_to ='profile_pics', blank = True)
    user_type = models.CharField(max_length = 10, choices = USER_CHOICES, default = 'Student')
    
    def __str__(self):
        return self.user.username

prj2/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'images/xyz.ico'%}" type="image/x-icon">
    <title>{% block title %} title {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/fontawesome.min.css">
    <script src="https://unpkg.com/sweetalert@2.1.2/dist/sweetalert.min.js"></script>
    <!-- Data table cdn -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css">
    <!-- font-awesome icon cdn -->
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
     <!-- DATE PICKER -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha512-mSYUmp1HYZDFaVKK//63EcZq4iFWFjxSL+Z3T/aCt4IO9Cejm03q3NKKYN6pFQzY0SBOr8h+eCIAZHPXcpZaNw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    {% block stylesheet %}  {% endblock %}
</head>
<body>
    {% include 'header.html' %}
    {% include 'nav.html' %}
    <main>
        <div class="container">
            <!-- {% for message in messages %}
              <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>

            {% endfor %} -->
            {% if messages %}
               {% for message in messages %}
                  <script>
                    swal("{{message}}", "Thank you ....","{{message.tags}}");
                  </script>
                {% endfor %}
            {% endif %}
            {% block content %}  {% endblock %}
        </div>
    </main>
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
    <!-- <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script> -->
    
    <!-- DATE PICKER -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    
    <script>
        //print, pc:present content, oc:old content
        function printDiv(divname){
          //alert('ok');
          var pc = document.getElementById(divname).innerHTML;
          var oc = document.body.innerHTML;
          document.body.innerHTML = pc;
          window.print();
          document.body.innerHTML = oc;
        }

      $(function(){
        setTimeout(function(){
          $('.alert').hide();
        },3000);   //1000 milisec = 1 second
        //modal
        $('#myModal').modal().show();

        //bootstrap datetime picker
        $("#id_dob").datepicker({
          format: "yyyy-mm-dd",
          autoclose:true,
          todayHighlight:true,
          orientation:"auto",
          endDate:"+0d"
        });

        // photo preview
        $("#id_photo").change(function(){
            readurl(this);
        });

        function readurl(input){
          var filepath = input.value;
          var allowextention = 
          /(\.jpg|\.png|\.gif)$/i;
          if(!allowextention.exec(filepath)){
              alert('Invalid File Type');
              input.value = '';
              return false;
          }
          else{
              if(input.files && input.files[0]){
                var reader = new FileReader();
                reader.onload = function(e){
                  $('.blah').attr('src', e.target.result).width(400);
                };
                reader.readAsDataURL(input.files[0]);

              }
          }
        }
        //Data table
        $('#myTable').DataTable({
          //"dom": '<f<t>ip>',
          "lengthMenu": [[5,10,25,50,-1],[5,10,25,50,"All"]]
        });
         
      });
    </script>
    {% block javascript %}  {% endblock %}
</body>
</html>

prj2/templates/email_form.html
{% extends 'base.html' %}

{% block title %} Email Send  {% endblock %}
{% block content %} 
        <form action="" method="POST" enctype="multipart/form-data" >
            {% csrf_token %}
            <div class="card w-75">
                <div class="card-header bg-warning text-light">
                 send Email
                </div>
                <div class="card-body">
                    {% if form.errors %} 
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        {% for field in form %}
                            {% for error in field.errors %}
                             <ul>
                                <li>{{ error|escape}}</li>
                             </ul>
                            {% endfor %}
                        {% endfor %}
                        
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                      </div>
                    <div class="form-group row">
                    {% endif %}

                    {% load crispy_forms_tags%}
                    {{ form | crispy}}
                       
                    <div class="form-group row">
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-success">Send</button>
                            <a href="{% url 'student:index' %}" class="btn btn-primary">Back</a>
                        </div>
                    </div>
                </div>
              </div>
         
           
        </form>
        
        <!-- <div class="form-group row">
            <a href="/index/" class="btn btn-primary">Back</a>
        </div> -->
{% endblock%}

prj2/templates/export.html
{% extends 'base.html' %}
{% block content %}
 <h2>Export data</h2>
 <h3>Exporting from Database</h3>
 <form method="POST" enctype="multipart/form-data">
   {% csrf_token %}
   <p>Select formate of file</p>
   <select name="file_format" id="" class="form-control my-3">
       <option>CSV</option>
       <option>JSON</option>
       <option>XLS</option>
       <option>HTML</option>
   </select>
   <br>
   <button class="btn btn-primary" type="submit">Export</button>
</form>
<a href="{% url 'home'%}">Back</a>
 {% endblock %}

prj2/templates/file1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
</head>
<body>
    <div class="container"> 
        <div id="div1">
        <h1>class 19</h1>
           <div class="sarin">
                <h2>Welcome to python programming world</h2>
                <span>my name is SARIN</span>
            </div>
        </div>   
     </div>
  
</body>
</html>

prj2/templates/header.html
{% load static %}
<header>
    <div class="container">
        <div class="row">
            <div>
                <h1>
                    <a href="">
                        <img src="{% static 'images/logo.png'%}" alt="" width="100%" >
                    </a>
                </h1>
            </div>
        </div>
    </div>
</header>

prj2/templates/homemap.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {{ title }} {% endblock %}
{% block content %} 
<div>
    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel" data-interval="3000">
        <div class="carousel-indicators">
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="{% static 'images/img1.jpg'%}" class="d-block w-100" style="height: 400px;" alt="...">
          </div>
          <div class="carousel-item">
            <img src="{% static 'images/img2.jpg'%}" class="d-block w-100" style="height: 400px;" alt="...">
          </div>
          <div class="carousel-item">
            <img src="{% static 'images/img3.jpg'%}" class="d-block w-100"  style="height: 400px;" alt="...">
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
</div>
<br>
<hr>
<div>
    <div class="mapouter"><div class="gmap_canvas"><iframe width="1120" height="400" id="gmap_canvas" src="https://maps.google.com/maps?q=east%20nakhalpara&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><a href="https://2piratebay.org"></a><br><style>.mapouter{position:relative;text-align:right;height:400px;width:1120px;}</style><a href="https://www.embedgooglemap.net">embed responsive google map</a><style>.gmap_canvas {overflow:hidden;background:none!important;height:400px;width:1120px;}</style></div></div>
</div>
<br>
<hr>
<div class="container">
    <table>
        <tr>
            <td><iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/yvgOl-RiAxM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></td>
            <td><iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/Jbv_5H2wDKs" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></td>
        </tr>
    </table>
    
</div>
{% endblock%}

prj2/templates/nav.html
{% load static %}
<header>
  <div class="container">
        <div class="row">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">
                  <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'images/xyz.ico'%}" alt=""></a>
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'student:export' %}">Export</a>
                      </li>
                      {% if request.user.is_authenticated %}
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'student:index' %}">Student</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'employee:list' %}">Employee</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'student:email' %}">Send email</a>
                      </li>
                      {% endif %}
                    </ul>
                    <ul class="navbar-nav ml-auto">
                      {% if request.user.is_authenticated %}
                      <li class="nav-item">
                        
                        <a href=""class="nav-link">
                          <img src="{{ request.session.profile_pic }}" class="rounded-circle article-img mr-2" width="30px" height= "30px"alt="">
                          Hi !! {{ request.user.username }}</a>
                      </li>
                      <li class="nav-item">
                        <a href="{% url 'student:logout' %}"class="nav-link">Logout</a>
                      </li>
                      {% else %}
                      <li class="nav-item">
                        <a href="{% url 'student:login' %}"class="nav-link">Login</a>
                      </li>
                      <li class="nav-item">
                        <a href="{% url 'student:register' %}"class="nav-link">Register</a>
                      </li>
                      {% endif %}
                    </ul>
                    </div>
                </div>
              </nav>
        </div>
    </div>
</header>
<br>