prj2/emsapp/urls.py
"""
"""
from django.contrib import admin
from django.urls import path
from emsapp import views

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'emsapp'


urlpatterns = [

    path('list/', views.EmployeeListView.as_view(), name = 'list'),
    path('create/', views.EmployeeCreateView.as_view(), name = 'create'),
    path('edit/<int:pk>', views.EmployeeUpdateView.as_view(), name = 'edit'),
    path('update/<int:pk>', views.EmployeeUpdateView.as_view(), name = 'update'),
    path('delete/<int:pk>', views.EmployeeDeleteView.as_view(), name = 'delete'),
    path('details/<int:pk>', views.EmployeeDetailView.as_view(), name = 'details'),
   
]

prj2/myapp/urls.py
"""
"""
from django.contrib import admin
from django.urls import path
from myapp import views

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'myapp'


urlpatterns = [
   
    path('details/<int:id>', views.show, name = 'details'),
    path('index/', views.index, name = 'index'),
    path('create/', views.create, name = 'create'),
    path('edit/<int:id>', views.edit, name = 'edit'),
    path('update/<int:id>', views.update, name = 'update'),
    path('delete/<int:id>', views.delete, name = 'delete'),
    path('email/', views.sendEmail, name = 'email'),
    path('register/', views.user_register, name = 'register'),
    path('login/', views.user_login, name = 'login'),
    path('logout/', views.user_logout, name = 'logout'),
    path('exportdata/', views.exportdata, name = 'export'),
]

prj2/prj2/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('std/', include(('myapp.urls', 'app_name'), namespace = 'student')),
    path('', views.home, name = 'home'),
    path('emp/', include(('emsapp.urls', 'app_name'), namespace = 'employee')),
    
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

prj2/templates/employee/create.html
{% extends 'base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %} 
        <form  method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="card w-75">
                <div class="card-header bg-warning text-light">
                  New Employee
                </div>
                <div class="card-body">
                    {% if form.errors %} 
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        {% for field in form %}
                            {% for error in field.errors %}
                             <ul>
                                <li>{{ error|escape}}</li>
                             </ul>
                            {% endfor %}
                        {% endfor %}
                        
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                      </div>
                    <div class="form-group row">
                    {% endif %}

                    <img src="{{ object.photo.url }}" class="blah" width="500" alt=""/>{{ object.photo }}

                    {% load crispy_forms_tags%}
                    {{ form | crispy}}
                       
                    <div class="form-group row">
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-success">Save</button>
                            <a href="{% url 'employee:list' %}" class="btn btn-primary">Back</a>
                        </div>
                    </div>
                </div>
              </div>
         
           
        </form>
        
        <!-- <div class="form-group row">
            <a href="/index/" class="btn btn-primary">Back</a>
        </div> -->
{% endblock%}

prj2/templates/employee/delete.html
{% extends 'base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %} 
        <form  method="POST" enctype="multipart/form-data">
            {% csrf_token %}       
           <!-- Button trigger modal -->
<!-- <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
    Launch static backdrop modal
  </button> -->
  
  <!-- Modal -->
  <div class="modal fade" id="myModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">Delete Employee</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p class="lead">Are you want to delete <strong>{{object_name}}?</strong></p>
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-danger" data-bs-dismiss="modal">Confirm Detete</button>
          <a href="{% url 'employee:list' %}" class="btn btn-warning"> back</a>
        </div>
      </div>
    </div>
  </div>
        </form>
        
        <!-- <div class="form-group row">
            <a href="/index/" class="btn btn-primary">Back</a>
        </div> -->
{% endblock%}

prj2/templates/employee/details.html
{% extends 'base.html' %}

{% block title %} Details {% endblock %}

{% block content %} 
        <form  method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="card w-75" id="report">
                <div class="card-header bg-warning text-light">
                  Employee Details
                </div>
                <div class="card-body">
                    {% if form.errors %} 
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        {% for field in form %}
                            {% for error in field.errors %}
                             <ul>
                                <li>{{ error|escape}}</li>
                             </ul>
                            {% endfor %}
                        {% endfor %}
                        
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                      </div>
                    <div class="form-group row">
                    {% endif %}

                    <div class="form-group row">
                        <label for="" class="col-sm-2">Employee Id</label>
                        <div class="col-sm-4">
                            {{object.id}}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="" class="col-sm-2">Name</label>
                        <div class="col-sm-4">
                            {{object.name}}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="" class="col-sm-2">Email</label>
                        <div class="col-sm-4">
                            {{object.email}}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="" class="col-sm-2">Dath of birth</label>
                        <div class="col-sm-4">
                            {{object.dob|date:'Y-m-d'}}
                        </div>
                    </div>
                     <br>  
                    <div class="form-group row">
                        <div class="col-sm-10">
                            <a href="{% url 'employee:list' %}" class="btn btn-primary">Back</a>
                            <button onclick="printDiv('report');" class="btn btn-warning">Print</button>
                        </div>
                    </div>
                </div>
              </div>
         
           
        </form>
        
        <!-- <div class="form-group row">
            <a href="/index/" class="btn btn-primary">Back</a>
        </div> -->
{% endblock%}

prj2/templates/employee/list.html
{% extends 'base.html' %}

{% block title %} {{ title }} {% endblock %}
{# {% block title %} {{ heading }} {% endblock %} #}
{% block content %}  
        <div>
            <div class="well">
                <a href="{% url 'employee:create' %}" class="btn btn-primary">Add New</a>
            </div>
           
            <table id="myTable" class="table table-striped DataTable">
                <thead>
                    <tr class="table-dark">
                        <th>Serial #</th>
                        <th>Employee Id</th>
                        <th>Employee Name</th>
                        <th>Email Address</th>
                        <th>Date of Birth</th>
                        <th>Gender</th>
                        <th>Salary</th>
                        
                        <th>Photo</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for emp in object_list %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ emp.id }}</td>
                        <td>{{emp.name}}</td> 
                        <td>{{ emp.email }}</td>
                        <td>{{ emp.dob|date:'Y-m-d' }}</td>
                        <td>{{ emp.gender }}</td>
                        <td>{{ emp.salary|floatformat:1 }}</td>
                       
                        <td>
                            <img src="{{ emp.photo.url }}" alt="no image" class="rounded-circle " width="50px"height="50px">
                        </td>
                        <td>
                            <a href="{% url 'employee:details' emp.id %}" class="btn btn-info" title="view"><i class="fa fa-eye" style="font-size:24px"></i></a>
                            <a href="{% url 'employee:edit' emp.id %}" class="btn btn-warning" title="Edit"><i class='fas fa-edit' style='font-size:24px'></i></a>
                            <a href="{% url 'employee:delete' emp.id %}" class="btn btn-danger" title="Delete"><i class="fa fa-trash" style="font-size:24px"></i></a>
                            
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            
        </div>
{% endblock %}