prj2/myapp/urls.py
"""
"""
from django.contrib import admin
from django.urls import path
from myapp import views

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'myapp'


urlpatterns = [
   
    path('details/<int:id>', views.show, name = 'details'),
    path('index/', views.index, name = 'index'),
    path('create/', views.create, name = 'create'),
    path('edit/<int:id>', views.edit, name = 'edit'),
    path('update/<int:id>', views.update, name = 'update'),
    path('delete/<int:id>', views.delete, name = 'delete'),
    path('email/', views.sendEmail, name = 'email'),
    path('register/', views.user_register, name = 'register'),
    path('login/', views.user_login, name = 'login'),
    path('logout/', views.user_logout, name = 'logout'),
    path('exportdata/', views.exportdata, name = 'export'),
]

prj2/prj2/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('std/', include(('myapp.urls', 'app_name'), namespace = 'student')),
    path('', views.home, name = 'home'),
    path('emp/', include(('emsapp.urls', 'app_name'), namespace = 'employee')),
    
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

prj2/myapp/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
# Create your models here.
class Student(models.Model):

    GENDER_CHOICES = [('Male', 'Male'),('Female', 'Female')]  #[(tuple)], ('Male', 'Male') one for desply one male for value
    id = models.AutoField(primary_key = True)
    name = models.CharField(max_length = 100)
    email = models.EmailField(unique = True, blank = True)
    dob = models.DateField(default = datetime.now, blank = True)
    gender = models.CharField(max_length = 6, choices = GENDER_CHOICES, default = 'Male', )
    
    def __str__(self):
        return f"Id: {self.id} Name: {self.name}"

class UserProfile(models.Model):
    USER_CHOICES = [('Admin','Admin'),('Student','Student'),('Employee','Employee')]
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    profile_pic = models.FileField(upload_to ='profile_pics', blank = True)
    user_type = models.CharField(max_length = 10, choices = USER_CHOICES, default = 'Student')
    
    def __str__(self):
        return self.user.username

prj2/myapp/forms.py
from django import forms
from myapp.models import Student, UserProfile
from django.contrib.auth.models import User

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = "__all__"

class EmailForm(forms.Form):
    email = forms.EmailField(max_length = 100, widget = forms.TextInput(attrs={'class':'form-control col-sm-4', 'placeholder':'email'}))
    subject = forms.CharField(max_length = 100, widget = forms.TextInput(attrs={'class':'form-control col-sm-4', 'placeholder':'subject'}))
    message = forms.CharField(required = False,max_length = 200, widget = forms.Textarea(attrs={'class':'form-control col-sm-4'}),label = ('  '))
    attach =  forms.FileField(required = False,widget=forms.ClearableFileInput(attrs={'multiple': True}))

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email','password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('profile_pic',)

prj2/templates/student/create.html
{% extends 'base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %} 
        <form action="{% url 'student:create' %}" method="POST">
            {% csrf_token %}
            <div class="card w-75">
                <div class="card-header bg-warning text-light">
                  New Student
                </div>
                <div class="card-body">
                    {% if form.errors %} 
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        {% for field in form %}
                            {% for error in field.errors %}
                             <ul>
                                <li>{{ error|escape}}</li>
                             </ul>
                            {% endfor %}
                        {% endfor %}
                        
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                      </div>
                    <div class="form-group row">
                    {% endif %}

                    {% load crispy_forms_tags%}
                    {{ form | crispy}}
                       
                    <div class="form-group row">
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-success">Save</button>
                            <a href="{% url 'student:index' %}" class="btn btn-primary">Back</a>
                        </div>
                    </div>
                </div>
              </div>
         
           
        </form>
        
        <!-- <div class="form-group row">
            <a href="/index/" class="btn btn-primary">Back</a>
        </div> -->
{% endblock%}

prj2/templates/student/details.html
{% extends 'base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %} 

        <form action="">
            <div id="report">
            <div class="card w-75">
                <div class="card-header bg-info text-light">
                  View Student
                </div>
                <div class="card-body">
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="Id">Id No:</label>
                        <div class="col-sm-6">
                            <input name="Id" type="text" id="id_id" value="{{ student.id }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="Id">Name</label>
                        <div class="col-sm-10">
                            <input name="name" type="text" id="id_name" value="{{ student.name }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="Id">Email</label>
                        <div class="col-sm-10">
                            <input name="email" type="text" id="id_email" value="{{ student.email }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="Id">Date of Birth</label>
                        <div class="col-sm-10">
                            <input name="dob" type="text" id="id_dob" value="{{ student.dob }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" for="Id">Gender</label>
                        <div class="col-sm-10">
                            <input name="gender" type="text" id="id_gender" value="{{ student.gender }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <a href="{% url 'student:index' %}" class="btn btn-primary">Back</a>
                            <button onclick="printDiv('report');" class="btn btn-warning">Print</button>
                        </div>
                    </div>
                </div>
              </div>
            </div>
           
        </form>
        
        <!-- <div class="form-group row">
            <a href="/index/" class="btn btn-primary">Back</a>
        </div> -->
{% endblock %}

prj2/templates/student/edit.html
{% extends 'base.html' %}

{% block title %} {{ title }} {% endblock %}
 
{% block content %}
        <form action="{% url 'student:update' student.id %}" method="POST">
            {% csrf_token%}
            <div class="card w-75">
                <div class="card-header bg-warning text-light">
                  Edit Student
                </div>
                <div class="card-body">
                    {% if form.errors %} 
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        {% for field in form %}
                            {% for error in field.errors %}
                             <ul>
                                <li>{{ error|escape}}</li>
                             </ul>
                            {% endfor %}
                        {% endfor %}
                        
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                      </div>
                    <div class="form-group row">
                    {% endif %}

                    {% load crispy_forms_tags%}
                    {{ form | crispy}}
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-success">Update</button>
                            <a href="{% url 'student:index' %}" class="btn btn-primary">Back</a>
                        </div>
                    </div>
                </div>
              </div>
         
           
        </form>
        
        <!-- <div class="form-group row">
            <a href="/index/" class="btn btn-primary">Back</a>
        </div> -->
{% endblock %}

prj2/templates/student/index.html
{% extends 'base.html' %}

{% block title %} {{ title }} {% endblock %}
{# {% block title %} List of Student {% endblock %} #}
{% block content %}  
        <div>
            <div class="well">
                <a href="{% url 'student:create' %}" class="btn btn-primary">Add New</a>
            </div>
           
            <table id="myTable" class="table table-striped DataTable">
                <thead>
                    <tr class="table-dark">
                        <th>Student Id</th>
                        <th>Student Name</th>
                        <th>Email Address</th>
                        <th>Date of Birth</th>
                        <th>Gender</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for std in students %}
                    <tr>
                        <td>{{ std.id }}</td>
                        <td>{{std.name }}</td>
                        <td>{{ std.email }}</td>
                        <td>{{ std.dob|date:'Y-m-d' }}</td>
                        <td>{{ std.gender }}</td>
                        <td>
                            <a href="{% url 'student:details' std.id %}" class="btn btn-info" title="view"><i class="fa fa-eye" style="font-size:24px"></i></a>
                            <a href="{% url 'student:edit' std.id %}" class="btn btn-warning" title="Edit"><i class='fas fa-edit' style='font-size:24px'></i></a>
                            <a href="{% url 'student:delete' std.id %}" class="btn btn-danger" title="Delete"><i class="fa fa-trash" style="font-size:24px"></i></a>
                            
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            
        </div>
{% endblock %}

prj2/templates/student/paging.html
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-left">
        {% if students.has_previous %}
        <li class="page-item">
        <a class="page-link" href="?page={{ students.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
        </a>
        </li>
        {% else %}
        <li class="page-item disabled">
        <a class="page-link" href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
        </a>
        </li>
        {% endif %}
        {% for i in students.paginator.page_range %}
        {% if students.number == i %}
            <li class="page-item active"><a class="page-link" href="#" >{{ i }} <span class="sr-only"></span></a></li>
        {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ i }}" >{{ i }}</a></li>
        {% endif %}
        {% endfor %}  
        {% if students.has_next %}
        <li class="page-item">
        <a class="page-link" href="?page={{ students.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
        </a>
        </li>
        {% else %}
        <li class="page-item disabled">
        <a class="page-link" href="#" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
        </a>
        </li>
        {% endif %}
    </ul>
    </nav> 


              <!-- <div class="pagination">
                <span class="step-links">
                    {% if students.has_previous %}          
                        <a href="?page={{ students.previous_page_number }}">previous</a>
                    {% endif %}
            
                    <span class="current">
                      {{ students.number }}
                    </span>
            
                    {% if students.has_next %}
                        <a href="?page={{ students.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div> -->